name: Feature request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to make **WOSdom Guides** better? 💡  
        Suggest a new feature or UX improvement here.

  - type: input
    id: summary
    attributes:
      label: Short summary
      description: A brief one-line description of the feature.
      placeholder: "e.g. Add search for guides by title"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem this solves
      description: What problem does this feature solve for players or contributors?
      placeholder: "When I'm trying to..., it's hard because..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you imagine this working?
      placeholder: "A search bar in the header that filters guides by title..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you thought about?
      placeholder: "I also considered..., but..."
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Mockups, links, or any other details.
      placeholder: "Add images, notes, or references here"
    validations:
      required: false
